
if (NOT CARBIN_PUBLIC_LIBS)
    set(CARBIN_PUBLIC_LIBS "")
endif ()

if (NOT CARBIN_SHARED__LIBS)
    set(CARBIN_SHARED__LIBS "")
endif ()

if (NOT CARBIN_STATIC_LIBS)
    set(CARBIN_STATIC_LIBS "")
endif ()

if (NOT CARBIN_INCLUDE_DIRS)
    set(CARBIN_INCLUDE_DIRS "")
endif ()