name: hercules-dev
channels:
  - conda-forge
  - defaults
  - mgottingen
dependencies:
  - gcc =8.5 # [linux]
  - gxx =8.5 # [linux]
  - sysroot_linux-64=2.17 # [linux]
  - melon
  - rocksdb
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark